server:
  port: 8888
encrypt:
  key:
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/<user>/<repo>
          skip-ssl-validation: false
          try-master-branch: false
          force-pull: true
          default-label: main
          searchPaths: '{application}'
