server:
  port: 8888
encrypt:
  key: ${CONFIG_ENCRYPT_KEY}
spring:
  cloud:
    config:
      server:
        git:
          # uri: https://github.com/<user>/<repo>
          uri: ${CONFIG_DATA_REPO}
          skip-ssl-validation: false
          try-master-branch: false
          force-pull: true
          default-label: main
          searchPaths: '{application}'
