server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri:
          skip-ssl-validation: false
          try-master-branch: false
          force-pull: true
          default-label: main
          searchPaths: '{application}'
