-- Sequence required to generate primary keys when Generation Strategy AUTO is used
CREATE SEQUENCE HIBERNATE_SEQUENCE;

CREATE TABLE CUSTOMER (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15),
    EMAIL VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ADDRESS (
    ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    TYPE VARCHAR(25),
    LINE1 VARCHAR(255),
    LINE2 VARCHAR(255),
    CITY VARCHAR(127),
    STATE VARCHAR(127),
    COUNTRY VARCHAR(127),
    ZIPCODE VARCHAR(25),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);
