server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: customer
  config:
    import: configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: validate
  zipkin:
    baseUrl: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: "*"
