server:
  port: 8085
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: order
  config:
    import: configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://<domain>.auth0.com/
  zipkin:
    baseUrl: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  host:
    customer: http://localhost:8081
    product: http://localhost:8083