scrape_configs:
  - job_name: 'Customer Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: 'Customer Service'
  - job_name: 'Product Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8083']
        labels:
          application: 'Product Service'
  - job_name: 'Order Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8085']
        labels:
          application: 'Order Service'
